[package]
name = "binpack-reader"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
byteorder = "1.5.0"
thiserror = "2.0.8"

[lib]
path = "src/lib.rs"

[[bin]]
name = "binpackreader"
path = "src/main.rs"

[profile.release]
debug = 1
